/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Employees;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author anasm
 */
public class EmployeeSystem extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeSystem
     */
    
    // Declare database connection objects
    protected static final String DBURL = "jdbc:mysql://localhost:3308/mycinemadb";
    protected static final String DBUSER = "root";
    protected static final String DBPASS = "";
    public static Connection connection;
    
    // Shows objects
    protected static Statement selectAllShows;
    protected static ResultSet showsResultSet;
    
    private ShowsForm showsForm = new ShowsForm();
    private MoviesForm moviesForm = new MoviesForm();
    private TheatersForm theatersForm = new TheatersForm();
    private CustomersForm customersForm = new CustomersForm();
    private EmployeesForm employeesForm = new EmployeesForm();
    private TicketsForm ticketsForm = new TicketsForm();
    

    
//    final static String allshowsQuery = "SELECT Show_ID, Movie_Name, Theater_Number, Date, Time, Available_Seats, Price FROM Shows INNER JOIN MOVIES ON Shows.Movie_ID = Movies.Movie_ID";
    private Employee currentEmployee;
    
    // Define the colors
    private Color blackColor = new Color(21, 22, 29);
    private Color blueColor = new Color(21, 122, 255);
    
    public void setCurrentEmployee(Employee currentEmployee) {
        this.currentEmployee = currentEmployee;
    }
    
    public void dbClose(){
        if(connection != null){
            try{
                connection.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/MyCinemaLogo.png")));
    }
    
    public EmployeeSystem() {
        initComponents();
        
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        showsMenu = new javax.swing.JButton();
        moviesMenu = new javax.swing.JButton();
        ticketsMenu = new javax.swing.JButton();
        theatersMenu = new javax.swing.JButton();
        customersMenu = new javax.swing.JButton();
        employeesMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        body = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee System | MyCinema");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(21, 22, 29));
        jPanel1.setLayout(new java.awt.GridLayout(8, 0, 0, 5));

        showsMenu.setBackground(new java.awt.Color(21, 122, 255));
        showsMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        showsMenu.setForeground(new java.awt.Color(255, 255, 255));
        showsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employees/images/icons8_play_36px.png"))); // NOI18N
        showsMenu.setText("Shows");
        showsMenu.setBorder(null);
        showsMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showsMenu.setFocusable(false);
        showsMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showsMenu.setIconTextGap(6);
        showsMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        showsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showsMenuActionPerformed(evt);
            }
        });
        jPanel1.add(showsMenu);

        moviesMenu.setBackground(new java.awt.Color(21, 22, 29));
        moviesMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        moviesMenu.setForeground(new java.awt.Color(255, 255, 255));
        moviesMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employees/images/icons8_movie_36px.png"))); // NOI18N
        moviesMenu.setText("Movies");
        moviesMenu.setBorder(null);
        moviesMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        moviesMenu.setFocusable(false);
        moviesMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        moviesMenu.setIconTextGap(6);
        moviesMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        moviesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviesMenuActionPerformed(evt);
            }
        });
        jPanel1.add(moviesMenu);

        ticketsMenu.setBackground(new java.awt.Color(21, 22, 29));
        ticketsMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ticketsMenu.setForeground(new java.awt.Color(255, 255, 255));
        ticketsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employees/images/icons8_ticket_36px.png"))); // NOI18N
        ticketsMenu.setText("Tickets");
        ticketsMenu.setBorder(null);
        ticketsMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ticketsMenu.setFocusable(false);
        ticketsMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ticketsMenu.setIconTextGap(6);
        ticketsMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ticketsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketsMenuActionPerformed(evt);
            }
        });
        jPanel1.add(ticketsMenu);

        theatersMenu.setBackground(new java.awt.Color(21, 22, 29));
        theatersMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        theatersMenu.setForeground(new java.awt.Color(255, 255, 255));
        theatersMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employees/images/icons8_movie_theater_36px.png"))); // NOI18N
        theatersMenu.setText("Theaters");
        theatersMenu.setBorder(null);
        theatersMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        theatersMenu.setFocusable(false);
        theatersMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        theatersMenu.setIconTextGap(6);
        theatersMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        theatersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theatersMenuActionPerformed(evt);
            }
        });
        jPanel1.add(theatersMenu);

        customersMenu.setBackground(new java.awt.Color(21, 22, 29));
        customersMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        customersMenu.setForeground(new java.awt.Color(255, 255, 255));
        customersMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employees/images/icons8_person_36px.png"))); // NOI18N
        customersMenu.setText("Customers");
        customersMenu.setBorder(null);
        customersMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customersMenu.setFocusable(false);
        customersMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        customersMenu.setIconTextGap(6);
        customersMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        customersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersMenuActionPerformed(evt);
            }
        });
        jPanel1.add(customersMenu);

        employeesMenu.setBackground(new java.awt.Color(21, 22, 29));
        employeesMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        employeesMenu.setForeground(new java.awt.Color(255, 255, 255));
        employeesMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employees/images/icons8_permanent_job_36px.png"))); // NOI18N
        employeesMenu.setText("Employees");
        employeesMenu.setBorder(null);
        employeesMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeesMenu.setFocusable(false);
        employeesMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employeesMenu.setIconTextGap(6);
        employeesMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        employeesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesMenuActionPerformed(evt);
            }
        });
        jPanel1.add(employeesMenu);

        jPanel2.setBackground(new java.awt.Color(21, 22, 29));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MyCinema | Employee System");

        logOutButton.setBackground(new java.awt.Color(21, 22, 29));
        logOutButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employees/images/icons8_lock_20px.png"))); // NOI18N
        logOutButton.setText("Log out");
        logOutButton.setBorder(null);
        logOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutButton.setFocusable(false);
        logOutButton.setIconTextGap(10);
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutButtonMouseExited(evt);
            }
        });
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Employees/images/icons8_person_36px.png"))); // NOI18N
        welcomeLabel.setText("<html> Welcome <br/> ");
        welcomeLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(welcomeLabel))
        );

        body.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(body, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            connection = DriverManager.getConnection(DBURL, DBUSER, DBPASS);
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        // Write the employee name in the welcome message
        welcomeLabel.setText(welcomeLabel.getText() + currentEmployee.getFirstName() + " " + currentEmployee.getLastName() + "</html>");
        
        // If the employee is a cashier hide the customers and employees menus
        if(currentEmployee.getRole_ID() == 2){
            customersMenu.setVisible(false);
            employeesMenu.setVisible(false);
        }
        
        ShowsForm.refreshTable();
        body.removeAll();
        body.add(showsForm);
        showsForm.show();
        
        
    }//GEN-LAST:event_formWindowOpened

    private void employeesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesMenuActionPerformed
        EmployeesForm.refreshTable();

        body.removeAll();
        body.add(employeesForm);
        employeesForm.show();

        // Change the colors
        showsMenu.setBackground(blackColor);
        moviesMenu.setBackground(blackColor);
        ticketsMenu.setBackground(blackColor);
        theatersMenu.setBackground(blackColor);
        customersMenu.setBackground(blackColor);
        employeesMenu.setBackground(blueColor);
    }//GEN-LAST:event_employeesMenuActionPerformed

    private void customersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersMenuActionPerformed
        CustomersForm.refreshTable();

        body.removeAll();
        body.add(customersForm);
        customersForm.show();

        // Change the colors
        showsMenu.setBackground(blackColor);
        moviesMenu.setBackground(blackColor);
        ticketsMenu.setBackground(blackColor);
        theatersMenu.setBackground(blackColor);
        customersMenu.setBackground(blueColor);
        employeesMenu.setBackground(blackColor);
    }//GEN-LAST:event_customersMenuActionPerformed

    private void theatersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theatersMenuActionPerformed
        TheatersForm.refreshTable();

        body.removeAll();
        body.add(theatersForm);
        theatersForm.show();

        // Change the colors
        showsMenu.setBackground(blackColor);
        moviesMenu.setBackground(blackColor);
        ticketsMenu.setBackground(blackColor);
        theatersMenu.setBackground(blueColor);
        customersMenu.setBackground(blackColor);
        employeesMenu.setBackground(blackColor);
    }//GEN-LAST:event_theatersMenuActionPerformed

    private void ticketsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketsMenuActionPerformed
        TicketsForm.refreshTable();

        body.removeAll();
        body.add(ticketsForm);
        ticketsForm.show();

        // Change the colors
        showsMenu.setBackground(blackColor);
        moviesMenu.setBackground(blackColor);
        ticketsMenu.setBackground(blueColor);
        theatersMenu.setBackground(blackColor);
        customersMenu.setBackground(blackColor);
        employeesMenu.setBackground(blackColor);
    }//GEN-LAST:event_ticketsMenuActionPerformed

    private void moviesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviesMenuActionPerformed
        MoviesForm.refreshTable();
        
        body.removeAll();
        body.add(moviesForm);
        moviesForm.show();
        
        // Change the colors
        showsMenu.setBackground(blackColor);
        moviesMenu.setBackground(blueColor);
        ticketsMenu.setBackground(blackColor);
        theatersMenu.setBackground(blackColor);
        customersMenu.setBackground(blackColor);
        employeesMenu.setBackground(blackColor);
    }//GEN-LAST:event_moviesMenuActionPerformed

    private void showsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showsMenuActionPerformed

        ShowsForm.refreshTable();

        body.removeAll();
        body.add(showsForm);
        showsForm.show();
        
        // Change the colors
        showsMenu.setBackground(blueColor);
        moviesMenu.setBackground(blackColor);
        ticketsMenu.setBackground(blackColor);
        theatersMenu.setBackground(blackColor);
        customersMenu.setBackground(blackColor);
        employeesMenu.setBackground(blackColor);
    }//GEN-LAST:event_showsMenuActionPerformed

    private void logOutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseEntered
        logOutButton.setBackground(new Color(44, 45, 52));
        
    }//GEN-LAST:event_logOutButtonMouseEntered

    private void logOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseExited
        logOutButton.setBackground(new Color(21, 22, 29));
    }//GEN-LAST:event_logOutButtonMouseExited

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // Show confirmation dialog
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Log out", JOptionPane.YES_NO_OPTION);
            
            // If the user chose yes
            if(confirm == JOptionPane.YES_OPTION){
                dbClose();
                this.dispose();
            }
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dbClose();        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane body;
    private javax.swing.JButton customersMenu;
    private javax.swing.JButton employeesMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton moviesMenu;
    private javax.swing.JButton showsMenu;
    private javax.swing.JButton theatersMenu;
    private javax.swing.JButton ticketsMenu;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
