/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Employees;
import Employees.EmployeeSystem;
import LoginPage.CustomerSignUp;
import com.raven.datechooser.SelectedDate;
import java.awt.Color;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import assets.TextFieldLimit;
import java.text.ParseException;
/**
 *
 * @author anasm
 */
public class NewAndUpdateCustomer extends javax.swing.JDialog {

    /**
     * Creates new form NewAndUpdateShow
     */

    private String selectedCustomerUser = null;

    public void setSelectedCustomerUser(String selectedCustomerUser) {
        this.selectedCustomerUser = selectedCustomerUser;
    }
    
    
    public NewAndUpdateCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
       
        initComponents();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        actionButton = new javax.swing.JButton();
        DoBField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        DoBLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();

        dateChooser.setForeground(new java.awt.Color(21, 122, 255));
        dateChooser.setTextRefernce(DoBField);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(21, 122, 255));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("New Customer");
        titleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        actionButton.setBackground(new java.awt.Color(21, 122, 255));
        actionButton.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        actionButton.setForeground(new java.awt.Color(255, 255, 255));
        actionButton.setText("Add Customer");
        actionButton.setBorder(null);
        actionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actionButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                actionButtonFocusGained(evt);
            }
        });
        actionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                actionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                actionButtonMouseExited(evt);
            }
        });
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });

        DoBField.setBackground(new java.awt.Color(246, 247, 249));
        DoBField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DoBField.setForeground(new java.awt.Color(21, 22, 29));
        DoBField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        DoBField.setCaretColor(new java.awt.Color(21, 22, 29));
        DoBField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(130, 142, 156));
        jLabel6.setText("Password");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(130, 142, 156));
        jLabel2.setText("Last name");

        lastName.setBackground(new java.awt.Color(246, 247, 249));
        lastName.setDocument(new TextFieldLimit(25));
        lastName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lastName.setForeground(new java.awt.Color(21, 22, 29));
        lastName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lastName.setCaretColor(new java.awt.Color(21, 22, 29));
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFocusLost(evt);
            }
        });
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(130, 142, 156));
        jLabel4.setText("First name");

        usernameLabel.setForeground(new java.awt.Color(255, 35, 71));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(130, 142, 156));
        jLabel1.setText("Username");

        firstNameLabel.setForeground(new java.awt.Color(255, 35, 71));
        firstNameLabel.setToolTipText("");

        firstName.setBackground(new java.awt.Color(246, 247, 249));
        firstName.setDocument(new TextFieldLimit(25)
        );
        firstName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        firstName.setForeground(new java.awt.Color(21, 22, 29));
        firstName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        firstName.setCaretColor(new java.awt.Color(21, 22, 29));
        firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFocusLost(evt);
            }
        });
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        DoBLabel.setForeground(new java.awt.Color(255, 35, 71));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(130, 142, 156));
        jLabel5.setText("Date of birth");

        lastNameLabel.setForeground(new java.awt.Color(255, 35, 71));

        passwordLabel.setForeground(new java.awt.Color(255, 35, 71));

        password.setBackground(new java.awt.Color(246, 247, 249));
        password.setDocument(new TextFieldLimit(25));
        password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        password.setForeground(new java.awt.Color(21, 22, 29));
        password.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        password.setCaretColor(new java.awt.Color(21, 22, 29));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });

        username.setBackground(new java.awt.Color(246, 247, 249));
        username.setDocument(new TextFieldLimit(30));
        username.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        username.setForeground(new java.awt.Color(21, 22, 29));
        username.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        username.setCaretColor(new java.awt.Color(21, 22, 29));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastName)
                            .addComponent(username)
                            .addComponent(password)
                            .addComponent(DoBField)
                            .addComponent(actionButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(DoBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(46, 46, 46))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(firstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameLabel))
                .addGap(4, 4, 4)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordLabel))
                .addGap(5, 5, 5)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DoBLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoBField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(actionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void actionButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_actionButtonFocusGained

    }//GEN-LAST:event_actionButtonFocusGained

    private void actionButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionButtonMouseEntered
        actionButton.setBackground(new Color(68, 149, 255));
    }//GEN-LAST:event_actionButtonMouseEntered

    private void actionButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionButtonMouseExited
        actionButton.setBackground(new Color(21, 122, 255));
    }//GEN-LAST:event_actionButtonMouseExited

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed
        boolean noEmptyFields = true;

        // Check if the first name is empty
        if(firstName.getText().trim().isEmpty()){
            firstNameLabel.setText("Please fill this field");
            noEmptyFields = false;
        }

        // Check if the last name is empty
        if(lastName.getText().trim().isEmpty()){
            lastNameLabel.setText("Please fill this field");
            noEmptyFields = false;
        }
        
        // Check if the username is empty
        if(username.getText().trim().isEmpty()){
            usernameLabel.setText("Please fill this field");
            noEmptyFields = false;
        }
        
        // Check if the password is empty
        if(password.getText().trim().isEmpty()){
            passwordLabel.setText("Please fill this field");
            noEmptyFields = false;
        }
        
        // Check if the DoB field is empty
        if(DoBField.getText().trim().isEmpty()){
            DoBLabel.setText("Please fill this field");
            noEmptyFields = false;
        }
        
        if(noEmptyFields){
            boolean validPassword = true;
            
            // Check if the password's length is less than 8 characters
            
            if(String.valueOf(password.getPassword()).trim().length() < 8){
                validPassword = false;
                passwordLabel.setText("Password must be at least 8 characters.");
            }
            
            // Get the selected date and convert it into LocalDate
            boolean validDoB = true;
            SelectedDate selectedDate = dateChooser.getSelectedDate();
            LocalDate DoB = LocalDate.of(selectedDate.getYear(), selectedDate.getMonth(), selectedDate.getDay()); 
            
            // Calculate the age 
            int age = CustomerSignUp.calculateAge(DoB);
            
            // Check if the age is greater than or equal 12 years
            if(age < 12){
                validDoB = false;
                JOptionPane.showMessageDialog(null, "you must be at least 12 years to sign up", "Sign up failed", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            
            // If the password and the DoB are correct open the connection
            if(validPassword && validDoB){
                
                // SQL Statements
                final String CHECK_USERNAME = "SELECT Username FROM Customers WHERE Username = ?";
                final String INSERT_CUSTOMER = "INSERT INTO CUSTOMERS VALUES(?, ?, ?, ?, ?)";
                final String UPDATE_CUSTOMER = "UPDATE CUSTOMERS SET Username = ?, FirstName = ?, LastName = ?, Password = ?, DoB = ? WHERE Username = \'" + selectedCustomerUser + "\' ";
                        
                // Declare database objects
                ResultSet resultSet = null;
                // To store the success message depends on the operation (Add or update)
                String successMessage;
                
                // To store the success message title depends on the operation (Add or update)
                String successTitle;

                // To store the sql statement that will be executed
                String InsertUpdateQuery;

                // If the operation is update
                if(selectedCustomerUser != null){
                    InsertUpdateQuery = UPDATE_CUSTOMER;
                    successTitle = "Update Customer";
                    successMessage = "Customer: [" + selectedCustomerUser + "] Updated Successfully";
                }else{
                    InsertUpdateQuery = INSERT_CUSTOMER;
                    successTitle = "Add Customer";
                    successMessage = "Customer added successfully";
                }

                try(
                    PreparedStatement checkUserStatement = EmployeeSystem.connection.prepareStatement(CHECK_USERNAME);
                    PreparedStatement newOrUpdateCustomerStatement = EmployeeSystem.connection.prepareStatement(InsertUpdateQuery);)
                {
                    checkUserStatement.setString(1, username.getText().trim());
                    resultSet = checkUserStatement.executeQuery();
                    

                    // Check if the username already exists
                    boolean isExist = false;
                    if(resultSet.next()){
                        if(selectedCustomerUser != null){
                            if(!selectedCustomerUser.equals(resultSet.getString(1))){
                                isExist = true;
                            }
                        }else{
                            isExist = true;
                        }
                    }
                    if(isExist){
                        JOptionPane.showMessageDialog(null, "Sorry, username already exists. Please try another one.", "Adding customer", JOptionPane.WARNING_MESSAGE);
                        usernameLabel.setText("Username already exists");
                    }
                    else{
                        java.sql.Date DateOfBirth = java.sql.Date.valueOf(DoB); 
                        
                        // Set the values to the insert statement
                        newOrUpdateCustomerStatement.setString(1, username.getText().trim());
                        newOrUpdateCustomerStatement.setString(2, firstName.getText().trim());
                        newOrUpdateCustomerStatement.setString(3, lastName.getText().trim());
                        
                        // Get the password
                        String pass = new String(password.getPassword());
                        newOrUpdateCustomerStatement.setString(4, pass.trim());
                        
                        newOrUpdateCustomerStatement.setDate(5, DateOfBirth);
                        
                        // Execute the insert statement
                        if(newOrUpdateCustomerStatement.executeUpdate() == 1){
                            // Show success dialog
                            JOptionPane.showMessageDialog(null, successMessage, successTitle, JOptionPane.INFORMATION_MESSAGE);
                        }
                        
                        // Clear the form
                        firstName.setText("");
                        lastName.setText("");
                        username.setText("");
                        password.setText("");
                        DoBField.setText("");
                        
                        // Refresh the table of movies
                        CustomersForm.refreshTable();
                        
                        // Dispose the dialog after the update
                        if(selectedCustomerUser != null){
                            this.dispose();
                        }
                    }
                    
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                }finally{
                    if(resultSet != null){
                        try{
                            resultSet.close();
                        }catch(SQLException e){
                            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }

        }
    }//GEN-LAST:event_actionButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           
        if(selectedCustomerUser != null){
            titleLabel.setText("Update Customer");
            actionButton.setText("Update Customer");

            final String SELECTED_CUSTOMER_QUERY = "SELECT Username, FirstName, LastName, Password, DoB FROM Customers WHERE Username = \'" + selectedCustomerUser + "\' ";
            try(Statement getSelectedCustomer = EmployeeSystem.connection.createStatement();
                ResultSet selectedCustomerResultSet = getSelectedCustomer.executeQuery(SELECTED_CUSTOMER_QUERY))
            {
                if(selectedCustomerResultSet.next()){
                    username.setText(selectedCustomerResultSet.getString(1));
                    firstName.setText(selectedCustomerResultSet.getString(2));
                    lastName.setText(selectedCustomerResultSet.getString(3));
                    password.setText(selectedCustomerResultSet.getString(4));
                    
                    // Set the old date of birth
                    try{
                        dateChooser.setSelectedDate(new SimpleDateFormat("yyyy-MM-dd").parse(selectedCustomerResultSet.getString(5)));
                    }catch(ParseException e){
                        System.out.println(e.getMessage());
                    }
                }
 
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void titleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleLabelMouseClicked
       
    }//GEN-LAST:event_titleLabelMouseClicked

    private void lastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusGained
        lastNameLabel.setText("");
    }//GEN-LAST:event_lastNameFocusGained

    private void lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFocusLost

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void firstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFocusGained
        firstNameLabel.setText("");
    }//GEN-LAST:event_firstNameFocusGained

    private void firstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFocusLost

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        passwordLabel.setText("");
    }//GEN-LAST:event_passwordFocusGained

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        usernameLabel.setText("");
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFocusLost

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAndUpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAndUpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAndUpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAndUpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewAndUpdateCustomer dialog = new NewAndUpdateCustomer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DoBField;
    private javax.swing.JLabel DoBLabel;
    private javax.swing.JButton actionButton;
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
