/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Customers;

import LoginPage.CustomerSignUp;
import assets.TextFieldLimit;
import com.raven.datechooser.SelectedDate;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author anasm
 */
public class Profile extends javax.swing.JInternalFrame {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        updateProfile();

    }

    public void updateProfile(){
        fullNameBefore.setText(CustomerSystem.getCurrentCustomer().getFirstName() + " " + CustomerSystem.getCurrentCustomer().getLastName());
        usernameBefore.setText(CustomerSystem.getCurrentCustomer().getUsername());
        DoBBefore.setText(CustomerSystem.getCurrentCustomer().getDoB());
        
        firstName.setText(CustomerSystem.getCurrentCustomer().getFirstName());
        lastName.setText(CustomerSystem.getCurrentCustomer().getLastName());
        username.setText(CustomerSystem.getCurrentCustomer().getUsername());
        password.setText(CustomerSystem.getCurrentCustomer().getPassword());
        
        try{
            dateChooser.setSelectedDate(new SimpleDateFormat("yyyy-MM-dd").parse(CustomerSystem.getCurrentCustomer().getDoB()));
        }catch(ParseException e){
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fullNameBefore = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        usernameBefore = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        DoBBefore = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        DoBLabel = new javax.swing.JLabel();
        DoBField = new javax.swing.JTextField();

        dateChooser.setForeground(new java.awt.Color(21, 122, 255));
        dateChooser.setDateFormat("yyyy-MM-dd");
        dateChooser.setTextRefernce(DoBField);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(21, 122, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Profile");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        fullNameBefore.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fullNameBefore.setForeground(new java.awt.Color(255, 255, 255));
        fullNameBefore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullNameBefore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customers/images/icons8_person_100px.png"))); // NOI18N
        fullNameBefore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fullNameBefore.setIconTextGap(16);
        fullNameBefore.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel3.setBackground(new java.awt.Color(21, 22, 29));

        usernameBefore.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameBefore.setForeground(new java.awt.Color(255, 255, 255));
        usernameBefore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customers/images/icons8_name_24px.png"))); // NOI18N
        usernameBefore.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        usernameBefore.setIconTextGap(40);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameBefore, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameBefore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(21, 22, 29));

        DoBBefore.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DoBBefore.setForeground(new java.awt.Color(255, 255, 255));
        DoBBefore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customers/images/icons8_calendar_24px.png"))); // NOI18N
        DoBBefore.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        DoBBefore.setIconTextGap(40);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DoBBefore, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DoBBefore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(fullNameBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fullNameBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(130, 142, 156));
        jLabel11.setText("First name");

        firstName.setBackground(new java.awt.Color(246, 247, 249));
        firstName.setDocument(new TextFieldLimit(25)
        );
        firstName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        firstName.setForeground(new java.awt.Color(21, 22, 29));
        firstName.setText(CustomerSystem.getCurrentCustomer().getFirstName());
        firstName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        firstName.setCaretColor(new java.awt.Color(21, 22, 29));
        firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFocusLost(evt);
            }
        });
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        firstNameLabel.setForeground(new java.awt.Color(255, 35, 71));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(130, 142, 156));
        jLabel12.setText("Username");

        password.setBackground(new java.awt.Color(246, 247, 249));
        password.setDocument(new TextFieldLimit(25));
        password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        password.setForeground(new java.awt.Color(21, 22, 29));
        password.setText(CustomerSystem.getCurrentCustomer().getPassword());
        password.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        password.setCaretColor(new java.awt.Color(21, 22, 29));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(130, 142, 156));
        jLabel13.setText("Last name");

        updateButton.setBackground(new java.awt.Color(21, 122, 255));
        updateButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.setBorder(null);
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateButton.setFocusable(false);
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateButtonMouseExited(evt);
            }
        });
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(130, 142, 156));
        jLabel6.setText("Password");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(21, 22, 29));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Update Your Profile");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(130, 142, 156));
        jLabel5.setText("Date of birth");

        username.setBackground(new java.awt.Color(246, 247, 249));
        username.setDocument(new TextFieldLimit(30));
        username.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        username.setForeground(new java.awt.Color(21, 22, 29));
        username.setText(CustomerSystem.getCurrentCustomer().getUsername());
        username.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        username.setCaretColor(new java.awt.Color(21, 22, 29));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        passwordLabel.setForeground(new java.awt.Color(255, 35, 71));

        usernameLabel.setForeground(new java.awt.Color(255, 35, 71));

        lastName.setBackground(new java.awt.Color(246, 247, 249));
        lastName.setDocument(new TextFieldLimit(25));
        lastName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lastName.setForeground(new java.awt.Color(21, 22, 29));
        lastName.setText(CustomerSystem.getCurrentCustomer().getLastName());
        lastName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        lastName.setCaretColor(new java.awt.Color(21, 22, 29));
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFocusLost(evt);
            }
        });
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });

        lastNameLabel.setForeground(new java.awt.Color(255, 35, 71));

        DoBLabel.setForeground(new java.awt.Color(255, 35, 71));

        DoBField.setBackground(new java.awt.Color(246, 247, 249));
        DoBField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DoBField.setForeground(new java.awt.Color(21, 22, 29));
        DoBField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        DoBField.setCaretColor(new java.awt.Color(21, 22, 29));
        DoBField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DoBField)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DoBLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lastName)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(usernameLabel))
                .addGap(4, 4, 4)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordLabel))
                .addGap(5, 5, 5)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DoBLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoBField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFocusGained
        firstNameLabel.setText("");
    }//GEN-LAST:event_firstNameFocusGained

    private void firstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFocusLost

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        passwordLabel.setText("");
    }//GEN-LAST:event_passwordFocusGained

    private void updateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseEntered
        updateButton.setBackground(new Color(68, 149, 255));
    }//GEN-LAST:event_updateButtonMouseEntered

    private void updateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseExited
        updateButton.setBackground(new Color(21, 122, 255));
    }//GEN-LAST:event_updateButtonMouseExited

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

        boolean noEmptyFields = true;

        // Check if the first name is empty
        if(firstName.getText().trim().isEmpty()){
            firstNameLabel.setText("Please fill this field");
            noEmptyFields = false;
        }

        // Check if the last name is empty
        if(lastName.getText().trim().isEmpty()){
            lastNameLabel.setText("Please fill this field");
            noEmptyFields = false;
        }
        
        // Check if the username is empty
        if(username.getText().trim().isEmpty()){
            usernameLabel.setText("Please fill this field");
            noEmptyFields = false;
        }
        
        // Check if the password is empty
        if(password.getText().trim().isEmpty()){
            passwordLabel.setText("Please fill this field");
            noEmptyFields = false;
        }
        
        // Check if the DoB field is empty
        if(DoBField.getText().trim().isEmpty()){
            DoBLabel.setText("Please fill this field");
            noEmptyFields = false;
        }
        
        if(noEmptyFields){
            boolean validPassword = true;
            
            // Check if the password's length is less than 8 characters
            
            if(String.valueOf(password.getPassword()).trim().length() < 8){
                validPassword = false;
                passwordLabel.setText("Password must be at least 8 characters.");
            }
            
            // Get the selected date and convert it into LocalDate
            boolean validDoB = true;
            SelectedDate selectedDate = dateChooser.getSelectedDate();
            LocalDate DoB = LocalDate.of(selectedDate.getYear(), selectedDate.getMonth(), selectedDate.getDay()); 
            
            // Calculate the age 
            int age = CustomerSignUp.calculateAge(DoB);
            
            // Check if the age is greater than or equal 12 years
            if(age < 12){
                validDoB = false;
                JOptionPane.showMessageDialog(null, "you must be at least 12 years to use the program", "Date of Birth Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // If the password and the DoB are correct open the connection
            if(validPassword && validDoB){
                
                // SQL Statements
                final String CHECK_USERNAME = "SELECT Username FROM Customers WHERE Username = ?";
                final String UPDATE_CUSTOMER = "UPDATE CUSTOMERS SET Username = ?, FirstName = ?, LastName = ?, Password = ?, DoB = ? WHERE Username = \'" + CustomerSystem.getCurrentCustomer().getUsername() + "\' ";
                        
                // Declare database objects
                ResultSet resultSet = null;
                // To store the success message 
                String successMessage = "Your information has been updated successfully.";
                
                // To store the success message title
                String successTitle = "Updating Your Profile";

                try(
                    PreparedStatement checkUserStatement = CustomerSystem.connection.prepareStatement(CHECK_USERNAME);
                    PreparedStatement UpdateCustomerStatement = CustomerSystem.connection.prepareStatement(UPDATE_CUSTOMER);)
                {
                    checkUserStatement.setString(1, username.getText().trim());
                    resultSet = checkUserStatement.executeQuery();
                    
                    // Check if the username already exists
                    boolean isExist = false;
                    if(resultSet.next()){ 
                        if(!CustomerSystem.getCurrentCustomer().getUsername().equals(resultSet.getString(1))){
                            isExist = true;
                        }
                    }
                    
                    if(isExist){
                        JOptionPane.showMessageDialog(null, "Sorry, username already exists. Please try another one.", "Updating Your Profile", JOptionPane.WARNING_MESSAGE);
                        usernameLabel.setText("Username already exists");
                    }
                    else{
                        java.sql.Date DateOfBirth = java.sql.Date.valueOf(DoB); 
                        
                        // Set the values to the insert statement
                        UpdateCustomerStatement.setString(1, username.getText().trim());
                        UpdateCustomerStatement.setString(2, firstName.getText().trim());
                        UpdateCustomerStatement.setString(3, lastName.getText().trim());
                        
                        // Get the password
                        String pass = new String(password.getPassword());
                        UpdateCustomerStatement.setString(4, pass);
                        
                        UpdateCustomerStatement.setDate(5, DateOfBirth);
                        
                        // Execute the update statement
                        if(UpdateCustomerStatement.executeUpdate() == 1){
                            // Show success dialog
                            JOptionPane.showMessageDialog(null, successMessage, successTitle, JOptionPane.INFORMATION_MESSAGE);
                       
                            // Update customer information
                            Customer customerAfterUpdate = new Customer();
                            customerAfterUpdate.setUsername(username.getText().trim());
                            customerAfterUpdate.setFirstName(firstName.getText().trim());
                            customerAfterUpdate.setLastName(lastName.getText().trim());
                            customerAfterUpdate.setPassword(pass);
                            customerAfterUpdate.setDoB(DateOfBirth.toString());

                            CustomerSystem.setCurrentCustomer(customerAfterUpdate);
                            CustomerSystem.updateWelcomeMessage();
                        }
                  
                        // Reload the window
                        updateProfile();
                        
                        
                    }
                    
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                }finally{
                    if(resultSet != null){
                        try{
                            resultSet.close();
                        }catch(SQLException e){
                            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }

        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        usernameLabel.setText("");
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFocusLost

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void lastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusGained
        lastNameLabel.setText("");
    }//GEN-LAST:event_lastNameFocusGained

    private void lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFocusLost

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoBBefore;
    private javax.swing.JTextField DoBField;
    private javax.swing.JLabel DoBLabel;
    private com.raven.datechooser.DateChooser dateChooser;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel fullNameBefore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameBefore;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
